services:
  app:
    restart: always
    build:
      context: .
    volumes:
      - ./:/app:cached
      - vendor:/app/vendor:delegated
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    restart: always
    image: mysql:8.0.28
    environment:
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true --authentication_policy=mysql_native_password
    hostname: db
    volumes:
      - mysql-data-app:/var/lib/mysql
    tty: true
volumes:
  vendor:
  mysql-data-app: